name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cover:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go
      - uses: actions/checkout@v2
      - run: make cover
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
